name: Hover
version: ${project.version}
main: me.venom.hover.Hover
api-version: 1.17
authors: [ VenomTR ]
description: If you have fly enabled, this plugin will teleport you off the ground, for optimal mining on a Prison server
permissions:
  hover.hover:
    description: Access to the /hover command
    default: op
commands:
  hover:
    description: Hover from your current position.
    usage: /<command>